### ISSUE TITLE
Move repository to lightning organization

### ISSUE THREAD

**Issue by t-bast** [lightning/lightning-rfc#925]
As discussed in https://lists.linuxfoundation.org/pipermail/lightning-dev/2021-October/003276.html, it seems like we have agreement to move the specifications to the https://github.com/lightning repository.

To summarize, the reasons we want to move are:

- avoid having the specifications and lnd's codebase in the same repository, as users get easily confused
- move away from the lightningnetwork organization because none of the implementers have admin access to it anymore

@Roasbeef could you give all of us admin rights to the `lightning` org?
We should then:

- migrate the `lightning-rfc` repository using github's migration tool
- migrate the original paper as well
- add a new `blips` repository (let's get this one rolling)

We should also remove links to https://lightning.network since it seems we also don't have access to that website and it's very outdated.

**Comment by Roasbeef** [comment]
And so shall it be done: https://github.com/lightning/lightning-rfc! 

Redirect looks to be working as well: https://github.com/lightningnetwork/lightning-rfc/pulls
